# Generated by Django 5.1.4 on 2024-12-11 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_alter_activity_latitude_alter_activity_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='image',
            field=models.ImageField(default='images/baloot.jpg', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='activity',
            name='person_limit',
            field=models.IntegerField(default=1),
        ),
    ]
