# Generated by Django 5.1.4 on 2024-12-11 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_activity_image_activity_person_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='person_limit',
            field=models.IntegerField(),
        ),
    ]
