# Generated by Django 5.1.4 on 2024-12-17 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0007_review'),
        ('activities', '0008_notification'),
    ]

    operations = [
    ]
