# Generated by Django 5.1.4 on 2024-12-16 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pics/defualt.png', null=True, upload_to='profile_pics/'),
        ),
    ]
